---
- name: ping PiStooges
  hosts: pistooges
  remote_user: pi
  gather_facts: False
  tasks:
    - name: test connection
      ping:
    - name: get model info
      shell: "/bin/cat /proc/device-tree/model | sed 's/\\x0//g'"
      register: model
    - debug: msg={{ model.stdout }}
