---
- name: Ping PiStooges
  hosts: pistooges
  remote_user: pi
  gather_facts: False
  vars:
      ansible_ssh_pass: raspberry
  tasks:
    - name: clean known hosts
      local_action: shell "ssh-keygen -R {{ inventory_hostname }} >/dev/null"
      ignore_errors: yes
      no_log: yes
    - name: test connection
      ping:
    - name: get model info
      shell: "/bin/cat /proc/device-tree/model | sed 's/\\x0//g'"
      register: model
    - debug: msg={{ model.stdout }}
