---
- name: Setup PiStooges
  hosts: pistooges
  vars:
    ansible_ssh_pass: raspberry
  remote_user: pi
  become: yes
  tasks:
    - name: Set authorized key
      authorized_key:
        user: pi
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    - hostname: name={{ ansible_host }}
    - name: expand filesystem
      command: raspi-config --expand-rootfs
      become: yes
      notify:
        - reboot
  handlers:
    - include: ../handlers/reboot.yml
      tags: system